const colors = {
  // plusmedical: '#038CFE',
  // skyBlue: '#E5F3FF',
  // water: '#CDE8FF',
  // orange: '#EB8C2F',
  // pink: '#FEF7F6',
  // red: '#EC5252',
  // purple: '#F3F3F9',
  // orangeHover: '#B46580',
  // // color names
  // black: '#343434',
  // white: '#FFF',
  // scarlet: '#FF475E',
  // blossom: '#FEF1F1',
  // blue: '#0390F7',
  // lightBlue: '#F4FBFF',
  // navy: '#043169',
  // gray: '#818E9D',
  // lavender: '#EBECF6',
  // focusOutline: '#3699FF',
  // motion names
  // blueHover: '3, 144, 247, 0.7',
  // error: '#FD3232',
  // listHover: '#F9FAFA',
  // element names
  // bgColor: '#F5F5F5',
  // bgColor: '#ccc',
  // border: '#D8D8D8',
  // bdInput: '#CCC',
  // disabledBlue: '#B5B5B5',
  // bgBadge: '#F5EBED',
  // bgSideNavHover: '#F5F8FA',
  // bottomTalkWrapper: '#F5F8FA',
  // bgMediaPaper: '#F6FAFC',
  // bgLabelIconGray: '#E4E4EB',
  // txtLabelIconGray: '#040849',
  // bgLabelIconBlue: '#E9EBF6',
  // txtLabelIconBlue: '#2C39A3',
  // bgLabelIconRed: '#FFE5ED',
  // txtLabelIconRed: '#FF004E',
  // bgIconButtonRed: '#F7E2E2',
  // txtDisabledButton: '#9F9F9F',
  // bgDropzone: '#FBFBFD',
  // bdDropzone: '#C3C3C3',
  // bgFocusedDropzone: '#E7E7FF',
  // bgPaperSelectableBox: '#FCFCFD',
  // selectedRadioFormTitle: '#333333',
  // checkedSelectedRadioFormTitle: '#2C39A3',
  // selectedRadioFormDescription: '#D3D3D3',
  // checkedSelectedRadioFormDescription: '#7B7B7B',
  // approvalBorder: '#D3D3D3',
  // switchBgNonActive: '#D3D3D3',
  // bottomFormBarBg: '#202123',
  // inputBorderColor: '#AEB4B9',
  // // estimate request label colors
  // progressingBg: '#D5F6E2',
  // progressingTxt: '#2DD070',
  // completedBg: '#CCE4FF',
  // completedTxt: '#0077FF',
  // cancelBg: '#FDEBCF',
  // cancelTxt: '#F39B13',
  // declineBg: '#FDEBCF',
  // declineTxt: '#F39B13',
  // // estimate label colors
  // unpublishedBg: '#D5D7DB',
  // unpublishedTxt: '#31394D',
  // createdBg: '#D5F6E2',
  // createdTxt: '#2DD070',
  // approvingBg: '#FFCCDB',
  // approvingTxt: '#FD004D',
  // remandBg: '#FDEBCF',
  // remandTxt: '#F39B13',
  // settledBg: '#DEDCF9',
  // settledTxt: '#5A51DE',
  // renewalApplicationBg: '#F4E5D7',
  // renewalApplicationTxt: '#C67D3B',
  // confirmingBg: '#FFCCDB',
  // confirmingTxt: '#FD004D',
  // createdAgentBg: '#CCE4FF',
  // createdAgentTxt: '#0077FF',
  // sentBg: '#CCE4FF',
  // sentTxt: '#0077FF',
  // expiredBg: '#FFCCDB',
  // expiredTxt: '#FD004D',
  // duplicateCorporateEstimateBg: '#CCE4FF',
  // duplicateCorporateEstimateTxt: '#0077FF',
  // // error colors
  // forbiddenTitle: '#fffffe',
  // forbiddenTxt: '#fff3ec',
  // forbiddenBg: '#55423d',
  // internalServerErrorTitle: '#094067',
  // internalServerErrorTxt: '#5f6c7b',
  // internalServerErrorBg: '#7fc1ff',
  // notFoundTitle: '#D05A6E',
  // notFoundTxt: '#594a4e',
  // notFoundBg: '#faeee7',
  // serviceUnavailableTitle: '#fffffe',
  // serviceUnavailableTxt: '#fffffe',
  // serviceUnavailableBg: '#516E41',
  // // number names
  // primary: '#D10068',
  // primaryHover: '#D10068',
  // // validate colors
  // warningBd: '#F39B13',
  // warningBg: '#FDEBCF',
};

export default colors;
